endlessm/ostree

- debian/libostree-dev.install
Without this change, it was being installed to
/usr/lib/girepository-1.0/girepository-1.0/OSTree-1.0.typelib, which is
not a valid location.
[endlessm/eos-shell#4447]
> Fix typelib installation directory

- debian/gir1.2-ostree.install
- debian/libostree-dev.install
The typelib file is needed at runtime and should be in the gir1.2
package while the gir file is only needed at buildtime and should be in
the dev package. This is how gtk and others handle the files:
$ dpkg-query -S /usr/lib/girepository-1.0/Gtk-3.0.typelib \
/usr/share/gir-1.0/Gtk-3.0.gir
gir1.2-gtk-3.0: /usr/lib/girepository-1.0/Gtk-3.0.typelib
libgtk-3-dev: /usr/share/gir-1.0/Gtk-3.0.gir
dh_girepository fails if the package containing the typelib file does
not begin with gir.
[endlessm/eos-shell#4447]
> Install gir components to the correct packages

- src/switchroot/ostree-prepare-root.c
prepare-root works with the mount that has been set up at /sysroot.
It creates a bind-mount within /sysroot (the deployment) and then moves
that mount to /sysroot.
Now we have 2 mounts both at /sysroot, and once we do switch_root, we will
never be able to unmount both of them. I'm not sure if this is ultimately
a kernel bug, but either way, ostree could do a bit more tidying up
after itself.
http://thread.gmane.org/gmane.linux.file-systems/92411
Easy way to reproduce:
1. Boot with rd.break param
2. At initramfs shell, run: ostree-prepare-root /sysroot
3. Observe two /sysroot mounts in /proc/mounts
Fix this by setting up the mounts at /sysroot.tmp, and unmounting the
original /sysroot before our new mount is MS_MOVEd on top of it.
https://github.com/endlessm/eos-shell/issues/4542
> prepare-root: avoid double-stacked /sysroot mount

- src/libostree/ostree-repo-checkout.c
We already set all file mtimes to 0 so that they are constant
over all checkouts, and can be made constant with a known value from
the system where the ostree was created.
However, this was not happening for directories. Zero their mtimes too.
This is important for shipping a fontconfig cache in the ostree;
the fontconfig cache files embed a directory mtime.
https://github.com/endlessm/eos-shell/issues/4601
> libostree: set directory mtimes to 0 on checkout

- src/switchroot/ostree-prepare-root.c
ostree-prepare-root was logging normal, informational messages
to stderr which the systemd unit points to the console.
To achieve silent boot, log these ordinary messages to stdout only.
https://github.com/endlessm/eos-shell/issues/2109
> ostree-prepare-root: log informational messages to stdout

- src/libostree/ostree-repo-prune.c
- src/libostree/ostree-repo.c
Prune has worked fine on bare repositories for some time, but now that
I finally try to delete data on the server side, I notice we weren't
actually enumerating content objects =/
That caused them to not be pruned.
https://bugzilla.gnome.org/show_bug.cgi?id=733458
(cherry picked from commit 1834a71b1f4856612e5d0638d1f82e9831e89a39)
Conflicts:
src/libostree/ostree-repo.c
[endlessm/eos-shell#2034]
> core: Do enumerate content objects in archive-z2 repositories

- src/libostree/ostree-repo-prune.c
This was intended in 16cdb46, but the merge on github ended up
preferring an older commit because the base of my merge request was from
before that.
[endlessm/eos-shell#4876]
> repo: Really stop using ostree_repo_traverse_commit_full()

- Makefile-ostree.am
- src/ostree/ot-admin-builtin-set-origin.c
- src/ostree/ot-admin-builtins.h
- src/ostree/ot-builtin-admin.c
Instead of editing the ostree files directly, backport the set-origin admin builtin so that we can correctly change branches and repo URLs. This will be used in eos-convert-system-qa to take a stable image and point it back at the appropriate branch in the staging/dev server.
[endlessm/eos-shell#4845]
> Add admin set-origin builtin for changing deployment branch

- src/libostree/ostree-repo.c
- src/ostree/ot-builtin-summary.c
- fix type of ret in ostree_repo_get_commit_sizes()
- fix size calculation to use gint64
- fix number of files calculation summary command
[endlessm/eos-shell#4730]
> Fix size calculation

- Makefile-tests.am
This test uses gpgme directly to verify the signatures, so it needs to
find the gpgme headers and link with gpgme to ensure the linker can
resolve the symbols.
> tests: Link test-gpg-verify-result with gpgme

- Makefile-ostree.am
- Makefile-tests.am
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.h
- src/ostree/main.c
- src/ostree/ot-builtin-pull.c
- src/ostree/ot-builtin-size-summary.c
- src/ostree/ot-builtins.h
- tests/libtest.sh
- tests/test-size-summary.sh
- tests/test-sizes.js
This PR adds support for reading the upstream commit size format. This is the first step in implementing https://github.com/endlessm/eos-shell/issues/1965
> Add commit size functionality

- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.h
- src/libostree/ostree-sysroot-deploy.c
- src/ostree/ot-builtin-pull.c
- src/ostree/ot-builtin-size-summary.c
Fix three issues:
* Immutable filesystem root prevented creating /endless symlink
* Legacy size metadata is large, which was causing daemon poll to fail
* Metadata only pull mode was ambiguously named
> Compat bugfixes

- src/libostree/ostree-sysroot-deploy.c
This reverts commit 9e1b046d361bd7fce6761878b278d600c08eef14.
[endlessm/eos-shell#5190]
> Revert "Don't make the root immutable"

- src/libostree/ostree-sysroot-deploy.c
Delete both /etc/.updated and /var/.updated on new deployments to support both typical conditions used by systemd units.
[endlessm/eos-shell#5426]
> Handle ConditionNeedsUpdate=/etc or /var

- src/libostree/ostree-sysroot-deploy.c
This reverts commit be1131def9a53804757866b448b6bebc30de7000.
Unfortunately, this breaks systemd's readahead implementation, which
tries to create /.readahead and /.readahead.new.
[endlessm/eos-shell#5190]
> Revert "Revert "Don't make the root immutable""

- src/libostree/ostree-fetcher.c
- tests/test-pull-mirror-summary.sh
There's no reason to keep them hidden.  I have a hard policy that
OSTree should *not* be used to carry secrets.  Things like host ssh
private keys should be set up out of band by an OS-external
configuration mechanism such as kickstart, cloud-init, etc.
We also assume that hiding binaries is not very useful as most
attackers would be able to find them on the Internet or (for
subscribed content) acting as a customer.
This fixes a bug with mirroring because we changed to take the
unmodified upstream objects rather than uncompress <-> recompress.
https://bugzilla.gnome.org/show_bug.cgi?id=748959
> fetcher: Use 0666 (-umask) for temporary files

- src/libostree/ostree-fetcher.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-metalink.c
- src/libostree/ostree-metalink.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
Bring a bunch of patches from upstream to fix timeout on pull. The key change here is https://github.com/endlessm/ostree/commit/c37341d717b8d703fc00b931a82240d6beca23eb, which depends directly on https://github.com/endlessm/ostree/commit/18c4ce69b7b8f57492524e5d85f48bf733b0f030. The upstream version of @magcius's change at https://github.com/endlessm/ostree/commit/b8dfbc84a760a2fd4ed524485d6afb3f6e66dea6 also replaces the version we had previously.
The other patches here are brought in to avoid major merge conflicts and fix bugs.
[endlessm/eos-shell#5697]
> Cherry-pick upstream patches to fix timeout on pull

- src/libostree/ostree-sysroot-deploy.c
This reverts commit 3c3a52793c09da29c02f36d67a953ed234a8726c.
Now that /.readahead has been moved to /var/.readahead, systemd's
readahead implementation should not be broken by an immutable
root.
[endlessm/eos-shell#5190]
> Revert "Revert "Revert "Don't make the root immutable"""

- src/libostree/ostree-repo-static-delta-core.c
out_deltas should be (transfer-container)
[endlessm/eos-shell#5572]
> static-delta: Fix annotation on ostree_repo_list_static_delta_names

- Makefile-tests.am
Since libreaddir-rand uses dlsym, it should link with libdl. Without
this, you may get an undefined symbol error.
https://phabricator.endlessm.com/T11513
> tests: Explicitly link libreaddir-rand with libdl

- tests/test-admin-deploy-karg.sh
- tests/test-admin-instutil-set-kargs.sh
On some systems there may be no root= argument, so the tests for
appending /proc/cmdline arguments will fail. Instead, loop over each of
the arguments in the host's /proc/cmdline and test that they're in the
constructed config file. That will actually test if ostree added all of
the system's /proc/cmdline args correctly.
https://phabricator.endlessm.com/T11513
> tests: Improve check for /proc/cmdline kargs

- src/libostree/ostree-repo-pull.c
The legacy object sizes format is not very space efficient,
causing it to easily exceed OSTREE_MAX_METADATA_SIZE.
To avoid bailing out, don't verify the size of that file.
This got missed on the last rebase. I hit this on the server when pulling old commits. @smspillaz could you review?
> Don't restrict the size of the legacy .sizes2 file

- src/libostree/ostree-repo-pull.c
OSTree function ostree_repo_pull_with_options starts a
series of operations that makes heavy use of the PullData's
cancellable.
This isn't effective, however, since nowhere in the code
the OtPullData.cancellable field is set. This is visible,
for example, when trying to cancel a Flatpak pull and nothing
happens, because the cancellable is not properly passed
to the pull data.
Fix that by setting the cancellable field of the pull data. It
owns a reference for safety reasons, and unreferences it at the
end of the operation.
https://phabricator.endlessm.com/T12885
> repo-pull: properly store the cancellable

- docs/manual/repo.md
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-libarchive.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- tests/basic-test.sh
In https://github.com/ostreedev/ostree/pull/330, OSTree changed to using
mtime 1 instead of 0 for every file added as part of a commit, but it's
unclear what that means when upgrading from systems with mtime set to 0,
so let's remove it for now for 3.0, to make it consistent with what
flatpak will also be doing in 3.0, as well as with the cache handling
hooks we have already in place in the eos-ostree-builder.
This reverts commit 0e9a875393ec038de5fdfa2aa0934ee03ff75334.
https://phabricator.endlessm.com/T13161
> Revert "repo: use OSTREE_TIMESTAMP (=1) for checked-out files"

- docs/manual/repo.md
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-libarchive.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- tests/basic-test.sh
This basically reverts the patch we got in yesterday (which was a direct revert of the original one) and brings in the [one that was actually integrated upstream today](https://github.com/ostreedev/ostree/commit/845dc651962b2c106872428336c9d81c2ed12432), to keep closer to the original project.
> Bring the upstream patch to get back to setting mtime to 0

- docs/manual/repo.md
- src/libostree/ostree-repo-private.h
- tests/basic-test.sh
Quoting Dan Nicholson in
<https://github.com/ostreedev/ostree/pull/330#issuecomment-245499099>
mtime of 0 has been the semantics of ostree deployments from basically
the beginning of the project. We (and others, see
flatpak/flatpak@b5204c9) rely on that fact when generating trees.
In particular, this affects caches that use the mtime of the
associated file or directory to determine if the cache is valid. By
arbitrarily changing the mtime of the files to something else, all
the caches we setup in the build are now invalidated. Preseeding
caches is really important to the user experience as it avoids
having the user wait while they're regenerated on first run.
Now, we could change our build infrastructure to preset all the
mtimes to 1 to match this change, but what does that do for our …
> repo: Revert default timestamp from 1 back to 0

- src/libostree/ostree-fetcher.c
Cherry picking this commit from upstream fixes the weird hang that some of us were experiencing when running GNOME Software for the first time.
https://phabricator.endlessm.com/T13285
> fetcher: Fix finalization deadlock

- src/ostree/ot-admin-builtin-status.c
It's useful to let non-root see the current system status.
Closes: #515
Closes: #516
Approved by: jlebon
https://phabricator.endlessm.com/T13466
> admin: Allow running status unlocked

- src/libostree/ostree-repo-static-delta-compilation.c
This will prevent including in the delta the bits to update files that
are not world readable, so that we don't run into a permissions problem
when applying the deltas from a bare-user repository that has a bare
repository set as its parent.
This is the case when updating flatpak apps/runtimes, as the temporary
directory created in ~/.local/share/flatpak/system-cache will be of
type bare-user with its parent set to /var/lib/flatpak which is a bare
repository in our case, as it's shared with the one at /ostree/repo.
https://phabricator.endlessm.com/T14159
> static-delta: Pretend that world unreadable objects are new objects

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-pull.c
- tests/test-core.js
A few fixes backported from upstream to be used in the new ostree-receive script. These will eventually go into the server package, but review is more convenient on master.
https://phabricator.endlessm.com/T5939
> Fixes for pull service

- src/libostree/ostree-fetcher.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-repo-pull.c
The summary file can get large, but it compresses well (something
which is not true of other files in the ostree repo which are
already compressed). By sending Accept-Encoding: gzip (and
handling the compressed results) we send a lot less data.
I set up the flathub repo (http://flathub.org/repo) to enable
gzip for the summary file (only), and the result is that the
331514 byte large summary was transferred in 122889 bytes.
On my (fast) network this decreased the time i took to do
"flatpak remote-ls flathub" by about 100msec.
(cherry picked from upstream commit be0c02d4f99fc071b18c21856b61c340bb44d5ae)
https://phabricator.endlessm.com/T17205
> fetcher: Send Accept-Encoding: gzip when downloading summary

- debian/ostree.install
- debian/ostree.maintscript
- debian/rules
These files now belong to the ostree-boot package but,
since it'd require considerable effort in updating core
packages.
https://phabricator.endlessm.com/T17204
> Don't remove ostree-boot files

- tests/test-compat-files.sh
Nowadays, 'ostree --version' prints the gpgme
feature prefixed with a - rather than a +.
This should be squashed to 9234affcf in a future
rebase.
https://phabricator.endlessm.com/T17204
> tests: Fix compat-files test

- src/libostree/ostree-repo-pull.c
- tests/pull-test.sh
- tests/test-compat-files.sh
This is almost entirely making fb0a4b7 work after a8fd37b. Some issues were because the rebasing of the patch wasn't applied quite right, others were things that a8fd37b changed in the pull behavior that needed to be handled, and one was a bug that turned into an error.
There are a couple other test fixes needed at the beginning of the series. After this, the test suite fully passes reliably for me.
https://phabricator.endlessm.com/T17204
> Make 2017.6 work

- debian/ostree.install
Our toolchain doesn’t currently support this profile, which results in
the man pages getting installed in `/<!nodoc>`, which is suboptimal.
https://phabricator.endlessm.com/T18832
> debian: Drop <!nodoc> profile from ostree.install due to lack of tooling

- Makefile-tests.am
- man/ostree.repo-config.xml
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot.c
- tests/admin-test.sh
- tests/test-admin-deploy-grub2.sh
- tests/test-admin-deploy-syslinux.sh
- tests/test-admin-deploy-uboot.sh
- tests/test-remotes-config-dir.js
This is a backport of https://github.com/ostreedev/ostree/pull/1151 and https://github.com/ostreedev/ostree/pull/1155 that allows fixing how /etc/ostree/remotes.d is used when remotes are added. This was breaking 2 cases we care about at Endless:
1. Flatpak using system ostree repo
2. ostree-receive service specifying a remotes config dir for a non-system repo
https://phabricator.endlessm.com/T19077
https://phabricator.endlessm.com/T18830
> Fix handling of /etc/ostree/remotes.d

- debian/changelog
- debian/libostree-1-1.symbols
https://phabricator.endlessm.com/T19293
See https://github.com/endlessm/ostree/pull/87 for the non-Debian part of this.
> debian: Add new symbols for OstreeRepoFinderOverride

- src/libostree/ostree-repo.c
Without this, ostree_repo_sign_commit throws a critical message when no
homedir is provided:
(ostree gpg-sign:5034): GLib-GIO-CRITICAL **: g_file_new_for_path: assertion 'path != NULL' failed
Closes: #1305
> lib/repo: Properly handle NULL homedir when signing commit

- Makefile-libostree.am
When compiling libostree, OSTREE_ENABLE_EXPERIMENTAL_API is managed via
config.h. However, g-ir-scanner can't use that since it gets confused
about the namespace of all the random macros. It won't include the
experimental APIs unless the macro is defined through another means.
Without this, none of the experimental APIs were being included in the
gir data.
This is a backport of the critical commit from ostreedev/ostree#1322. I really need this on the infrastructure side, so if it's merged I'll follow with a merge to the xenial branch.
https://phabricator.endlessm.com/T19126
> build: Define OSTREE_ENABLE_EXPERIMENTAL_API for g-ir-scanner

- debian/ostree.install
- debian/rules
Use of rofiles-fuse is causing a kernel hang on the Xenial armhf kernel.
kernel: INFO: task flatpak-builder:30930 blocked for more than 120 seconds.
kernel:       Tainted: G        W       4.4.0-98-generic #121-Ubuntu
kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
kernel: flatpak-builder D c0bf5e84     0 30930  30928 0x00000000
kernel: [<c0bf5e84>] (__schedule) from [<c0bf63c0>] (schedule+0x50/0xa8)
kernel: [<c0bf63c0>] (schedule) from [<c04a2dfc>] (kmap_high+0x110/0x240)
kernel: [<c04a2dfc>] (kmap_high) from [<c031f2d4>] (kmap+0x40/0x44)
kernel: [<c031f2d4>] (kmap) from [<c0512af0>] (write_pipe_buf+0x44/0x88)
kernel: [<c0512af0>] (write_pipe_buf) from [<c051337c>] (__splice_from_pipe+0x114/0x1a8)
kernel: [<c051337c>] (__splice_from_pipe) from …
> Disable rofiles-fuse on ARM

- Makefile-tests.am
Creating the symlink will cause make to try to build rofiles-fuse, which
will fail if it's disabled. Normally I wouldn't disable rofiles-fuse,
but it's triggering a hang in our ARM Xenial builder's kernel in splice.
I'm sure that's fuse's fault, but for now I just need to disable
rofiles-fuse there and found --disable-rofiles-fuse didn't actually
work.
Closes: #1325
This is a backport of https://github.com/ostreedev/ostree/commit/2e9fea8fa54f431a6e4cc2993d0b4b2ca18a6070.
https://phabricator.endlessm.com/T18830
> tests: Don't symlink rofiles-fuse if it's disabled

- apidoc/ostree-experimental-sections.txt
- src/libostree/libostree-experimental.sym
- src/libostree/ostree-core.c
- src/libostree/ostree-ref.h
- src/libostree/ostree-remote.h
Backporting a few fixes which have already been accepted upstream, to improve the GIR file for OSTree with experimental API enabled.
> T19126 GIR fixes

- debian/changelog
- debian/libostree-1-1.symbols
Put a new release in the changelog, so that other packages can bump
their dependency on OSTree as necessary.
---
The Debian part of: https://github.com/endlessm/ostree/pull/95
> debian: Add ostree_remote_get_type() to symbols file

- src/libostree/ostree-repo-finder.c
- src/libostree/ostree-repo-refs.c
- src/libostree/ostree-soup-form.c
- src/libostree/ostree-soup-uri.c
By default, unless it’s const, an (out) GHashTable will be assumed to be
(transfer full). That means the binding needs to free all the items in
the hash table, plus the table itself.
However, all the GHashTables we use have free functions set already, so
freeing the hash table will free its items. This results in a
double-free.
Fix that by ensuring we annotate such (out) hash tables as (transfer
container). Also annotate some other hash tables as (transfer none)
where appropriate, for clarity.
This fixes OSTree.Repo.list_collection_refs() in the Python bindings.
Closes: #1341
Approved by: dbnicholson
---
Downstream pull of https://github.com/ostreedev/ostree/pull/1341. It needs to be merged to `xenial` once approved for master.
> lib/repo: Add (transfer) annotations to various GHashTable arguments

- Makefile-tests.am
- apidoc/ostree-experimental-sections.txt
- src/libostree/libostree-experimental.sym
- src/libostree/ostree-autocleanups.h
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-prune.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-repo.h
- tests/test-concurrency.py
This is a backport of ostreedev/ostree#1346 and ostreedev/ostree#1343 (still unmerged at this time). This adds the repository locking mechanism I implemented and wires it up for transactions and prunes. I added a lot more locking and features in ostreedev/ostree#1292, but this should cover what I believe to be the major concurrency issues we have.
https://phabricator.endlessm.com/T16736
> Basic repository locking

- debian/changelog
- debian/libostree-1-1.symbols
Registers the API symbols from #99.
https://phabricator.endlessm.com/T16736
> Add symbols for new repo locking APIs

- apidoc/ostree-experimental-sections.txt
- src/libostree/libostree-experimental.sym
- src/libostree/ostree-remote.c
- src/libostree/ostree-remote.h
- tests/test-repo-finder-config.c
When using dynamic remotes (LAN and USB), we cannot use their name with
the common remote related ops (ostree_repo_remote_...) because ostree
doesn't keep this type of remotes in its internal hash table.
Unfortunately this means that we cannot access the URL of those remotes
either (in order to e.g. set the right URL for those remotes in
Flatpak).
Since the URL is actually stored in a key file that belongs to the
OstreeRemote, then we can simply allow users access to it through a
getter.
So this patch adds a method that allows to return the URL directly from
the OstreeRemote without having to go through the OstreeRepo.
The test-repo-finder-config is also updated by this patch to check if
the URL is correct.
Merged upstream as a1745e1a79ea1c41cc62e91b346a2a9961997a76. …
> lib/remote: Add a method to return the URL

- debian/libostree-1-1.symbols
This was an API added to support writing the compat signature files from
the ostree gpg-sign builtin. Both that usage and the symbol itself have
been removed since the compat signatures are no longer being created.
See #103 for main branch PR.
https://phabricator.endlessm.com/T17367
> Remove ostree_repo_delete_compat_signature from symbols file

- debian/control
- debian/rules
Add avahi-glib as a build dependency and use the configure option
--with-avahi to try to ensure that ostree compiles with avahi support,
which is necessary for P2P updates to work.
https://phabricator.endlessm.com/T20662
> debian: Compile with avahi support

- src/libostree/ostree-repo-finder-avahi.c
- src/libostree/ostree-repo-pull.c
This is a normal case when running unit tests in client code
on continuous integration infrastructure. When those tests are
running they will set G_DEBUG=fatal-warnings which will cause
the program to abort if a warning is emitted. Instead, emit
a debug message if the problem was that we couldn't connect to
the daemon.
https://phabricator.endlessm.com/T16682
> avahi: Don't complain with g_warning if the daemon wasn't running

- src/libostree/ostree-repo-pull.c
For P2P pulls ostree adds temporary remotes and removes them in
find_remotes_cb(). However, if an OstreeRepoFinderResult gets freed
during the course of that function, the OstreeRemote in the result is
freed but a pointer to it remains in the remotes_to_remove array. This
means that when _ostree_repo_remove_remote() gets called on it at the
end of the function it will fail. In my case the resulting error was
"OSTree-CRITICAL **: _ostree_repo_remove_remote: assertion 'remote->name
!= NULL' failed" but I think it could also seg fault.
This commit adds a reference to the remote so it can be properly removed
when we're finished with it.
Closes: #1450
Approved by: giuseppe
> lib/pull: Properly remove temporary remotes

- src/libostree/ostree-repo-pull.c
Currently users of the find_remotes_async()/pull_from_remotes_async()
functions have no way to specify a commit hash to use instead of the
latest one available. This commit implements an "override-commit-ids"
option analogous to the one used by ostree_repo_pull_with_options().
It's accomplished by returning OstreeRepoFinderResult objects pointing
to the given commit checksum(s) regardless of which ones were available
from the remotes, but in the future this implementation could be
improved to take into account the commits advertised by the remotes.
One effect of this is that flatpak will have the ability to downgrade
apps that use collection IDs
(https://github.com/flatpak/flatpak/issues/1309).
Closes: #1425
Approved by: pwithnall
(cherry picked from commit …
> lib/pull: Allow specific commits in P2P updates

- src/libostree/ostree-repo-commit.c
In ostree_repo_abort_transaction, if we pass a cancellable and it gets
canceled, then the function may fail to fully clean up the transaction
state. This was happening e.g. when the ostree_repo_pull_with_options
call got cancelled.
To fix this, as suggested by Colin Walters, we set the passed
cancellable as NULL, in order for it to be ignored.
https://github.com/ostreedev/ostree/issues/1491
> pull: Ignore the cancellable when aborting a transaction

- src/libostree/ostree-sysroot-deploy.c
Without this, a previous entry with a deployment version found from the
version metadata would not have it's entry changed when a new deployment
is installed. That's a problem with our grub implementation that will
continue to boot the previous entry as long as it can find its title.
Without appending the deployment index, it will never change.
https://phabricator.endlessm.com/T22114
> lib/deploy: Always append index to bootloader title

- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-fetcher-soup.c
- src/libostree/ostree-fetcher-util.c
- src/libostree/ostree-fetcher-util.h
- src/libostree/ostree-metalink.c
- src/libostree/ostree-metalink.h
- src/libostree/ostree-repo-pull.c
- src/ostree/ostree-trivial-httpd.c
- tests/test-pull-repeated.sh
This is a straight backport of upstream’s:
* https://github.com/ostreedev/ostree/pull/1599 (omitting [this commit](https://github.com/ostreedev/ostree/pull/1599/commits/b4ea90b89449a498d92b405e8629d3175a2b15cc) because it didn’t apply cleanly, but it’s just a code cleanup)
* https://github.com/ostreedev/ostree/pull/1594
* https://github.com/ostreedev/ostree/pull/1600 (not yet merged upstream; one merge conflict due to [this downstream patch](https://github.com/endlessm/ostree/commit/9ba58ef5c38cae1c0ebabefae8e3921d3e40d60d))
> T22555 Retry downloads on flaky networks

- src/libostree/ostree-repo-pull.c
In case of some kind of race or other weirdness we might be getting
non-matching versions of summary.sig and summary, where summary.sig
is the latest version. Currently we're saving them to the cache
directly after downloading them successfully, but they will then fail
to gpg validate. Then on the next run we'll keep using the cached files
even if they are incorrect, until summary.sig changes upstream.
This changes the order so that we verify the signatures before saving
to the cache, thus ensuring that we don't end up in a stuck state.
Fixes https://github.com/ostreedev/ostree/issues/1523
Closes: #1529
(cherry picked from commit c4c2b5ebd155f9d17531db4ab9c2516699132745)
Signed-off-by: Robert McQueen <rob@endlessm.com>
https://phabricator.endlessm.com/T22886
> pull: Don't save summary to cache before validating signatures

- src/libostree/ostree-repo-pull.c
If pulling a static delta fails (due to one part of it missing from a
mirror, for example), retry the entire pull operation with
disable-static-deltas=true.
This is a functional, but ugly approach to fixing the problem, and a
neater solution may be adopted upstream in future. If so, this commit
should be dropped and replaced with the upstream solution:
https://github.com/ostreedev/ostree/pull/1612
https://phabricator.endlessm.com/T22873
> lib/repo-pull: Retry pulls without static deltas if they fail

- man/ostree.repo-config.xml
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-refs.c
- src/libostree/ostree-repo.c
- src/ostree/ot-builtin-commit.c
- tests/test-auto-summary.sh
This commits adds and implements a boolean repo config option called
"change-update-summary" which updates the summary file every time a ref
changes (additions, updates, and deletions).
The main impetus for this feature is that the `ostree create-usb` and
`flatpak create-usb` commands depend on the repo summary being up to
date. On the command line you can work around this by asking the user to
run `ostree summary --update` but in the case of GNOME Software calling
out to `flatpak create-usb` this wouldn't work because it's running as a
user and the repo is owned by root. That strategy also means flatpak
can't update the repo metadata refs for fear of invalidating the
summary.
Another use case for this relates to LAN updates. Specifically, the
component of eos-updater that generates …
> config: Add a core/change-update-summary option

- src/libostree/ostree-repo-pull.c
Normally, a configured remote will only serve refs with one associated
collection ID, but temporary remotes such as USB drives or LAN peers can
serve refs from multiple collection IDs which may use different GPG
keyrings. So the OstreeRepoFinderMount and OstreeRepoFinderAvahi classes
create dynamic OstreeRemote objects for each (uri, keyring) pair. So if
for example the USB mounted at /mnt/usb serves content from the
configured remotes "eos-apps" and "eos-sdk", the OstreeRepoFinderResult
array returned by ostree_repo_find_remotes_async() will have one result
with a remote called something like
file_mnt_usb_eos-apps.trustedkeys.gpg and the list of refs on the USB
that came from eos-apps, and another result with a remote
file_mnt_usb_eos-sdk.trustedkeys.gpg and the list of refs from …
> lib/repo-pull: Use correct keyring for dynamic remotes

- debian/changelog
- debian/libostree-1-1.symbols
ostree_mutable_tree_remove and ostree_repo_get_min_free_space_bytes are
backported in Endless.
https://phabricator.endlessm.com/T23819
> Add backported symbols to debian/libostree-1-1.symbols

- man/ostree-create-usb.xml
- src/ostree/ot-builtin-create-usb.c
Currently on Endless OS, the OSTree ref for the operating system is
something like os/eos/amd64/eos3, so that's what gets passed to `ostree
create-usb` when copying the OS to a USB drive (for offline updates).
However, when eos-updater checks for updates it pulls the metadata for a
candidate commit and in so doing updates that eos3 ref to point to the
partial commit being examined as a potential update rather than the
deployed commit. This causes `ostree create-usb` to fail with an error
like "No such metadata object
7fb045cb2d1f1f3a81bfc157c6128ff443eb56350315b9536bdb56aee0659863.dirtree".
OSTree creates deployment refs that look like "ostree/1/1/0" to maintain
a pointer to the deployed commit, but create-usb can't use these because
it shows up in the summary as just a ref, not a …
> create-usb: Add a --commit option

- src/ostree/ot-builtin-create-usb.c
Change the create-usb command so that it always creates the destination
repository using the "archive" mode, rather than using archive mode when
xattrs aren't supported and bare-user otherwise. This has a few
advantages:
1. The archive mode works with FAT filesystems, which is what most
USB drives are, and which doesn't support xattrs.
2. At least in some quick testing I did, archive mode is about
twice as performant as bare-user mode, in terms of how long it takes for
the create-usb command to complete.
3. This ensures that a tool can safely change the permissions on
".ostree/repo" and subdirectories after create-usb completes, which is
important for Endless since otherwise you can't use `ostree create-usb`
as root and then `flatpak create-usb` as a non-root user on the same USB
drive …
> create-usb: Always use archive mode

- src/libostree/ostree-repo-commit.c
- tests/installed/nondestructive/itest-pull-space.sh
We want a case where we can disable the min-free-space check. Initially,
it felt like to add a OSTREE_REPO_PULL_FLAGS_DISABLE_FREE_SPACE_CHECK but
the problem is prepare_transaction() does not have a OstreeRepoPullFlags
parameter which we can parse right here. On top of it, prepare_transaction()
enforces min-free-space check and won't let the transaction proceed if
the check failed.
This is pretty bad in conjunction with "inherit-transaction" as what
Flatpak uses. There is no way to disable this check unless we remove
it altogether from prepare_transaction.
This issue came out to light when flatpak wasn't able to write metadata
after fetching from remote:
[uajain@localhost ~]$ flatpak remote-info flathub org.kde.Platform//5.9
error: min-free-space-size 500MB would be exceeded
Metadata …
> lib/repo-commit: Relax min-free-space check in prepare_transaction()

- src/libostree/ostree-bootloader-grub2.c
OSTree recently gained support[1] for recognizing the Debian-style
/boot/grub/grub.cfg path in addition to the existing support for the Red
Hat-style /boot/grub2/grub.cfg. With this, it decides to run
grub-mkconfig in ostree_sysroot_write_deployment_with_options() by
calling ostree_bootloader_write_config(). However grub-mkconfig is
disabled on Endless OS since the grub.cfg is hand-written and doesn't
need updates[2] and therefore returns a non-zero exit status. This
causes operations such as "ostree admin unlock --hotfix" and "ostree
admin upgrade" to fail.
So this commit effectively reverts the Debian grub support, by making
_ostree_bootloader_grub2_query() always return TRUE with out_is_active
set to FALSE, so that grub-mkconfig is not called and the operations
above succeed. In the …
> grub2: Disable use of grub-mkconfig on Endless

- tests/pull-test.sh
- tests/pull-test2.sh
glib 2.59.2 uses a non-breaking space instead of a space to
separate the quantity and unit in g_format_size() so update
our test to handle both a plain space and a non-breaking space.
See https://gitlab.gnome.org/GNOME/glib/issues/1625
Closes: #1818
> tests: Update for glib 2.59.2

- configure.ac
This reverts commit 40a54e3d273296c7aa8f2ea783a03bf55a80cbd4.
This commit reverts the version bump from 2019.1 to 2019.2 so that the
version of ostree in Endless reports to be 2019.1. This is more accurate
since 2019.2 hasn't been released yet. This was my fault since I rebased
onto upstream master rather than the 2019.1 release commit.
https://phabricator.endlessm.com/T25195
> Revert "Post-release bump"

- tests/test-sizes.js
Recent GJS changed how byte arrays are unpacked with some assumptions
that they are likely strings. Manually use get_child_value() and
get_byte() to ensure the correct value is parsed when checking the
`ostree.sizes` metadata.
This should really be split into 2 parts since the `deep_unpack()` is upstream but the additional `objType` byte is only downstream. Just looking for review right now.
https://phabricator.endlessm.com/T27213
> tests/sizes.js: Fix byte array unpacking

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot.c
When trying to deploy on a vfat partitions, such as the EFI ESP, we
fail to create the loader symlink, and deployment fails.
We'd like to use sd-boot, which only works with the ESP, so we need
a way to deploy without using symlinks.
For a quick and dirty minimally invasive fix, I've made deployment
create a bogus symlink - a text file named loader.sln that contains
the name of the real loader dir.
I've modified systemd-boot to read these bogus symlinks as well.
https://phabricator.endlessm.com/T27040
> deploy: Create fake symlinks when on FAT filesystems

- man/ostree.repo-config.xml
- src/libostree/ostree-repo.c
This reverts commit 5233c3dc4686dd992e63c94c69e47fd6730acee8.
Disable LAN updates by default. See the ticket below for the rationale;
essentially this feature is not in a working state and carries a
significant performance cost. One can still enable LAN updates on a
specific computer; see the documentation for core.default-repo-finders
in ostree.repo-config(5).
https://phabricator.endlessm.com/T27862
> Revert "Revert "lib/repo-pull: Disable LAN updates by default""

- Makefile-switchroot.am
- src/switchroot/ostree-prepare-root.c
This reverts the following commits:
304abee9eb "prepare-root: Fix compilation with --with-static-compiler"
298c601d88 "ostree-prepare-root: Log journal message after finding deployment"
Which were causing ostree-prepare-root to crash on the EC-100. We can
safely revert these since we don't use rpm-ostree.
https://phabricator.endlessm.com/T27976
> prepare-root: Revert logging changes for rpm-ostree

- apidoc/ostree-sections.txt
- src/libostree/libostree-released.sym
- src/libostree/ostree-async-progress.c
- src/libostree/ostree-async-progress.h
- tests/test-symbols.sh
This allows copying the state from one OstreeAsyncProgress object to
another, atomically, without invoking the callback. This is needed in
libflatpak, in order to chain OstreeAsyncProgress objects so that you
can still receive progress updates when iterating a different
GMainContext than the one that the OstreeAsyncProgress object was
created under.
https://phabricator.endlessm.com/T26965
> libostree: Add ostree_async_progress_copy_state()

- src/libostree/ostree-async-progress.c
Here is the change that I made due to an upstream review comment, that was eventually merged. I'll include it in our fork as a fixup commit to avoid rebase conflicts in the future.
https://phabricator.endlessm.com/T26965
> Resolve upstream review comment

- src/libostree/ostree-bootloader-uboot.c
- src/libostree/ostree-sysroot-deploy.c
Add support for a devicetree directory at /usr/lib/modules/$kver/dtb/.
In ARM world a general purpose distribution often suppports multiple
boards with a single operating system. However, OSTree currently only
supports a single device tree, which does not allow to use the same
OSTree on different ARM machines. In this scenario typically the boot
loader selects the effective device tree.
This adds device tree directory support for the new boot artefact
location under /usr/lib/modules. If the file `devicetree` does not
exist, then the folder dtb will be checked. All devicetrees are hashed
into the deployment hash. This makes sure that even a single devicetree
change leads to a new deployment and hence can be rolled back.
The loader configuration has a new key "devicetreepath" which contains …
> deploy: support devicetree directory

- src/libostree/ostree-bootloader-uboot.c
- src/libostree/ostree-sysroot-deploy.c
This reverts commit 61c50925fb9218f94562ef07e26c2c1a8b978ba1.
The main purpose of T29416 is test the commit provided by upstream. And,
we have the test result and gave feedback. Besides, it does not meet the
criteria we expected which provides dtb folder with the same structure
as the way device tree binaries get installed by the official Linux
kernel. We have already fed back the idea to upstream [1]. So, it is the
time to revert the commit ("deploy: support devicetree directory").
https://phabricator.endlessm.com/T29416
[1] https://github.com/ostreedev/ostree/pull/2001#issuecomment-605816752
> Revert "deploy: support devicetree directory"

- src/boot/dracut/ostree.conf
Without reproducible images, a rebuild of the initrd will create a
different image file (due to things like creation time of the files in
the cpio archive) even if the actual contents in it are exactly the
same, adding an unnecessary download during updates.
Adding 'reproducible=yes' avoids this and creates the same image files
for the same content.
https://phabricator.endlessm.com/T30443
> dracut: Create reproducible images

- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/ostree/ot-dump.c
- tests/test-summary-view.sh
These are cherry-picks of the following two PRs from upstream OSTree, which improve gnome-software/flatpak/OSTree’s performance on high-latency network connections:
* https://github.com/ostreedev/ostree/pull/2166
* https://github.com/ostreedev/ostree/pull/2167
There were some minor cherry-pick conflicts, noted in the commit messages.
I would also have liked to cherry pick https://github.com/ostreedev/ostree/pull/2205, but there were too many conflicts and I would have essentially had to rewrite a significant chunk of it, which didn’t seem worth it for the impact the changes would have. We’ll get them when we rebase OSTree.
https://phabricator.endlessm.com/T30404
> T30404 Backport latency fixes

- src/libostree/ostree-repo-static-delta-compilation.c
Without this you can't create a scratch delta from GI. While here,
switch the deprecated allow-none annotations to nullable.
(cherry picked from commit 3e527d94473aeae5fbd64158cec47ebb4de41722)
We don't actually need this in EOS. However, I'd like this so that I can exercise the eosostree server code locally.
https://phabricator.endlessm.com/T18707
> lib/deltas: Annotate from checksum as nullable

- bash/ostree
- man/ostree-pull-local.xml
- man/ostree-pull.xml
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- src/ostree/ot-builtin-pull.c
- tests/test-pull-collections.sh
2 backports from upstream that add an option to skip verification of commit bindings on pulls. This isn't really needed on master but it's convenient for me for testing things locally that will eventually run on the server. Upstream PRs were ostreedev/ostree#2253 and ostreedev/ostree#2254.
https://phabricator.endlessm.com/T20138
> Allow skipping verification binding on pulls

- bash/ostree
- man/ostree-pull-local.xml
- man/ostree-pull.xml
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- src/ostree/ot-builtin-pull.c
- tests/pull-test.sh
- tests/pull-test2.sh
- tests/test-pull-collections.sh
2 backports from upstream that add an option to skip verification of commit bindings on pulls. This is needed for some work to merge together our current per arch `eos-$arch` repos into one `eos` repo. Our OS repos have many older released commits that lack collection and ref bindings but now live in a repository that has a collection ID. I also found at least one commit that had the wrong ref bindings from the early days when we were getting the bindings in place.
Upstream PRs were ostreedev/ostree#2253 and ostreedev/ostree#2254.
https://phabricator.endlessm.com/T20138
> [Infrastructure] Allow skipping verification binding on pulls

- src/libostree/ostree-repo-pull.c
- tests/test-local-pull-depth.sh
- tests/test-pull-depth.sh
Backports for fixing a local pull with infinite depth. This is the master companion to #176 which is really just for the convenience of local testing.
Upstream PR at ostreedev/ostree#2267.
https://phabricator.endlessm.com/T20138
> Fix pull-local with depth

- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- tests/basic-test.sh
- tests/test-local-pull-depth.sh
- tests/test-pull-depth.sh
This is for the benefit of the repo merging I'm trying to do where I want to pull the entire history of one local repo into another. There were a couple issues running this that were fixed upstream.
Upstream PR at ostreedev/ostree#2267.
https://phabricator.endlessm.com/T20138
> infra: Fix pull-local with depth

- src/libostree/ostree-repo-pull.c
Currently if a file path contains a special character such as '\', and
that character is encoded into a file:// URI that is passed to
ostree_repo_pull_with_options(), the percent encoding will remain in the
path passed to g_file_new() (in the case of backslash %5C) and the pull
will then fail with a file not found error. This is an important edge
case to handle because by default on many Linux distributions a
filesystem with no label is mounted at a path based on its UUID, and
this is then passed to systemd-escape by Flatpak (when
--enable-auto-sideloading was used at compile time) to create a symbolic
link such as this which contains backslashes:
$ ls -l /run/flatpak/sideload-repos/
total 0
lrwxrwxrwx 1 mwleeds mwleeds 55 Mar  9 14:21 …
> Fix translation of file:// URIs into paths

- debian/README.Endless
- debian/rules
This was kept to support tests in eos-updater, but that's been updated now to use the standalone `ostree-trivial-httpd` shipped in the ostree-tests package.
https://phabricator.endlessm.com/T31384
> Drop trivial-httpd builtin

- debian/control
- debian/libostree-1-1.symbols
Packaging changes to support the repo locking API backport in #184. Technically the package version used in the symbols file should be `2020.8+dev<something>` but we don't know what `<something>` is until the merge has been made and jenkins generates the new version. A bare `2020.8` version is good enough for our usage.
https://phabricator.endlessm.com/T31868
> Repo locking API packaging

- man/ostree-summary.xml
- src/libostree/ostree-core.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/ostree/ot-dump.c
- tests/test-summary-view.sh
The commit metadata `version` key is well established but getting it for
a remote commit is cumbersome since the commit object needs to be
fetched and loaded. Including it in the summary additional metadata
allows a much more convenient view of what each of the remote refs
represents.
(cherry picked from commit 6fbf759279ca9908e0c7ceb2a3af75b1180fa8a1)
https://phabricator.endlessm.com/T33099
This is a backport of https://github.com/ostreedev/ostree/pull/2535 so that the summary generated on our ostree server includes the OS version on our commits.
> lib/repo: Add commit version metadata to summary metadata

- src/libostree/ostree-repo-pull.c
- src/libotutil/ot-variant-builder.c
A couple fixes from upstream that coincide with Debian's [proposed bullseye update](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006905). The delta commit partial fix is important. The infinite recursion one I haven't seen in practice but the code was clearly wrong before and crash if it was reached.
https://phabricator.endlessm.com/T33209
> Recent ostree backport fixes

- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-pull.c
- src/libotutil/ot-variant-builder.c
A couple fixes from upstream that coincide with Debian's [proposed bullseye update](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006905). The delta commit partial fix is important. The infinite recursion one I haven't seen in practice but the code was clearly wrong before and crash if it was reached. The `g_file_get_child` fix is important if glib is ever updated. I don't know if that will happen on eos4.0, but I think it's a good idea to be prepared.
https://phabricator.endlessm.com/T33209
> Recent ostree backport fixes for eos4.0

- src/libostree/ostree-repo-pull.c
- src/libotutil/ot-variant-builder.c
A couple fixes from upstream that coincide with Debian's [proposed bullseye update](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006905). The delta commit partial fix is important. The infinite recursion one I haven't seen in practice but the code was clearly wrong before and crash if it was reached. Since this is for 3.9, we may only want critical fixes, so I'm fine if the infinite recursion one is dropped.
https://phabricator.endlessm.com/T33209
> Recent ostree backport fixes for eos3.9

- src/libostree/ostree-bootloader-grub2.c
This reverts commit 344474a916afda24a84932faf95a20578631d36c. All systems have been converted to declare the desired bootloader in the repository configuration `sysroot.bootloader` option. On grub systems this is set to `none` so that only the boot loader spec entries are updated. This and the reverted commit should be dropped during the next upstream rebase.
https://phabricator.endlessm.com/T34161
> Revert "grub2: Disable use of grub-mkconfig on Endless"

- configure.ac
Backports from upstream to handle gpgme detection with newer releases of gpgme. It now has a `gpgme` pkg-config file and apparently the `AM_PATH_GPGME_PTHREAD` autoconf macro no longer works.
> Fix gpgme detection

- debian/control
- debian/rules
This avoids library conflicts during the transition to GNOME 43, in which core apps and libraries have switched to libsoup3, which conflicts with libsoup2.4.
We still build-depend on libsoup2.4, because it's used in the test suite and installed-tests.
Closes: #1016589
(cherry picked from commit 53261afd32e3772e9ee1484432f6bbb16c38500f)
https://phabricator.endlessm.com/T35040
> Build with libcurl http backend instead of libsoup2.4
