endlessm/ostree

src/switchroot/ostree-prepare-root.c

When booting from a system with /boot on the main partition, set up
an appropriate bind mount during boot. The ostree runtime binary
expects to be able to access the bootloader configs at /boot.
[endlessm/eos-shell#5332]

prepare-root: set up /boot bind-mount for single partition systems

---

src/libostree/ostree-sysroot-deploy.c

Systemd units using ConditionNeedsUpdate=/etc run if the mtime of
/etc/.updated is newer than /usr. Since /usr has an mtime of 0, there's
no way to have an older .updated file.
Remove the file from the new deployment's /etc regardless of where it
came from to ensure that these systemd units run when booting new
deployments. This will provide a method to run services only on upgrade.
[endlessm/eos-shell#5364]

deploy: Delete /etc/.updated from new deployments

---

.gitignore
src/libostree/ostree-repo-pull.c
tests/.gitignore
tests/libtest.sh

This PR is just a cherry-pick of the commits @magcius is putting upstream here: https://bugzilla.gnome.org/show_bug.cgi?id=753336
[endlessm/eos-shell#5404]

Add a queue for scanning

---

src/libostree/ostree-lzma-common.c
src/libostree/ostree-lzma-compressor.c
src/libostree/ostree-lzma-decompressor.c
src/libostree/ostree-repo-static-delta-compilation.c
src/libostree/ostree-repo-static-delta-processing.c

This also includes one error handling fix for generating static deltas.

Fix errors in applying static deltas

---

src/libostree/ostree-repo-prune.c
src/libostree/ostree-repo-traverse.c

https://phabricator.endlessm.com/T10881

Don't fail pruning partial commits

---

Makefile-tests.am
Makefile.am
tests/libostreetest.c
tests/test-auto-summary.sh

Various fixes for distcheck and other things required for jenkins and OBS. I think all of these are appropriate upstream, but I haven't submitted them yet.
https://phabricator.endlessm.com/T11513

ostree 2016.5 build fixes

---

debian/changelog
debian/control
debian/copyright
debian/patches/Terminate-individual-tests-after-half-an-hour.patch
debian/patches/series

https://phabricator.endlessm.com/T13340

Updated debian packaging to OSTree 2016.10

---

src/libostree/ostree-repo.c

https://phabricator.endlessm.com/T14786

Backport fixes for list_objects bindings

---

src/libostree/ostree-fetcher.c

When fetching data to membuf we were moving the input stream we got
from the soup session to the other thread where the stream was closed
after splicing it into the memory output stream. Current libsoup from
master does not quite handle it gracefully as there are some races
inside which may lead to the hang. The bug for libsoup was reported,
but the fix is still not agreed upon.
https://bugzilla.gnome.org/show_bug.cgi?id=778135
To work it around we do the splicing in the same thread where the
download happened, so the main thread just receives the memory buffer.
https://phabricator.endlessm.com/T15146

fetcher: Avoid races inside libsoup input streams

---

debian/libostree-1-1.symbols

https://phabricator.endlessm.com/T15909

debian: Add new compression symbol to Debian symbols file

---

Makefile-tests.am
src/libostree/ostree-sysroot-upgrader.c
tests/libtest.sh
tests/test-admin-upgrade-endoflife.sh

https://phabricator.endlessm.com/T17124

 Allow commits to mark refs as EOL, replaced by others 

---

src/libostree/ostree-bloom.c

Submitted and merged upstream as https://github.com/ostreedev/ostree/pull/1231. We also need to merge this into our `eos3.3` branch, which we can do with a merge from `master` after this has been merged.
---
https://phabricator.endlessm.com/T19388

-Wconversion bloom filter fixes

---

Makefile-libostree-defines.am
Makefile-libostree.am
apidoc/ostree-experimental-sections.txt
src/libostree/libostree-experimental.sym
src/libostree/ostree-autocleanups.h
src/libostree/ostree-core-private.h
src/libostree/ostree-repo-finder-avahi.c
src/libostree/ostree-repo-finder-mount.c
src/libostree/ostree-repo-finder-override.c
src/libostree/ostree-repo-finder-override.h
src/libostree/ostree.h

Cherry-picked from upstream (they will all be in the upcoming 2017.13 release):
* https://github.com/ostreedev/ostree/pull/1281
* https://github.com/ostreedev/ostree/pull/1293
* https://github.com/ostreedev/ostree/pull/1301
* https://github.com/ostreedev/ostree/pull/1303
---
https://phabricator.endlessm.com/T19293

Various OSTree bug fixes

---

apidoc/ostree-experimental-sections.txt
src/libostree/libostree-experimental.sym
src/libostree/ostree-core.c
src/libostree/ostree-ref.h
src/libostree/ostree-remote.h

Version of https://github.com/endlessm/ostree/pull/95 for the `xenial` branch (made with `git checkout xenial; git merge master`)

T19126 GIR fixes (xenial)

---

debian/changelog
debian/libostree-1-1.symbols

https://phabricator.endlessm.com/T20078

Add symbol for ostree_remote_get_url

---

src/ostree/ot-builtin-find-remotes.c
tests/test-find-remotes.sh
tests/test-repo-finder-mount-integration.sh

https://phabricator.endlessm.com/T20662

Add a --finders option to find-remotes

---

src/libostree/ostree-repo-pull.c

https://phabricator.endlessm.com/T22644

T22644 no from-scratch deltas

---

src/libostree/ostree-fetcher-curl.c
src/libostree/ostree-fetcher-soup.c
src/libostree/ostree-fetcher-util.c
src/libostree/ostree-fetcher-util.h
src/libostree/ostree-metalink.c
src/libostree/ostree-metalink.h
src/libostree/ostree-repo-pull.c
src/ostree/ostree-trivial-httpd.c
tests/test-pull-repeated.sh

https://phabricator.endlessm.com/T22555

T22555 Backport network retries to eos3.3

---

src/libostree/ostree-repo-commit.c

If there’s a problem while aborting a transaction, store the error but
don’t report it until the end of the function — do a best effort at
clearing the rest of the transaction state first (since most of it
cannot fail).
If cleanup_tmpdir() fails (which, arguably, should not be a
showstopper), this allows a caller to recover and start a new
transaction in future.
(Backported from upstream commit
2d2f218669e6230edaf6329913a2b2c1cda590ed.)
https://phabricator.endlessm.com/T22972
---
Already reviewed and merged upstream [here](https://github.com/ostreedev/ostree/pull/1626).

lib/repo-commit: Delay propagation of errors from abort_transaction()

---

src/libostree/ostree-repo-commit.c

If ostree_repo_prepare_transaction() fails, we should reset the
repository’s state so that the failed call was essentially idempotent.
Do that by calling ostree_repo_abort_transaction() on the failure path.
Typically, the way for preparing a transaction to fail is for its
GCancellable to be triggered, rather than because any of the operations
involved in preparing a transaction are particularly failure prone.
Closes: #1647
(Backported from upstream commit
abff8b8cfac00203062362ad506ffdb14f1da6ef.)
https://phabricator.endlessm.com/T23091

lib/repo-commit: Abort a transaction if preparing it fails

---

man/ostree.repo-config.xml
src/libostree/ostree-repo-commit.c
src/libostree/ostree-repo-private.h
src/libostree/ostree-repo.c

https://phabricator.endlessm.com/T13698

Upstream cherry picks min-free-space-size

---

src/libostree/ostree-sysroot-deploy.c

We can now deploy our custom initramfs + kernel efi blobs.
This will only happen when the ESP is mounted (ie: we're deploying
to a fat filesystem).
https://phabricator.endlessm.com/T27521

deploy: Handle efi blobs

---

debian/ostree-boot.install

Packaging companion to #203 to add the new `ostree-finalize-staged-hold.service` unit.
https://phabricator.endlessm.com/T33775

Debian packaging for automount /boot fix
